spring:
  application:
    name: postservice
  datasource:
    url: jdbc:postgresql://localhost:5432/postservice
    username: neil
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

config:
  import: "configserver:http://localhost:8071"

server:
  port: 8081
  servlet:
    context-path: /postservice

info:
  message: "postservice default"

logging:
  level:
    root: DEBUG