spring:
  application:
    name: postservice
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postservice}"
    username: ${SPRING_DATASOURCE_USERNAME:neil}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: "${RABBIT_HOST:localhost}"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8082
  servlet:
    context-path: /postservice

info:
  message: "postservice default"

logging:
  level:
    root: DEBUG