spring:
  application:
    name: postservice
  datasource:
    url: jdbc:postgresql://localhost:5432/postservice
    username: neil
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8082
  servlet:
    context-path: /postservice

info:
  message: "postservice default"

logging:
  level:
    root: DEBUG