spring:
  application:
    name: userservice
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/userservice}"
    username: ${SPRING_DATASOURCE_USERNAME:neil}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: "${RABBIT_HOST:localhost}"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

server:
  port: 8081
#  servlet:
#    context-path: /userservice

info:
  app:
    name: "userservice"
    description: "userservice"
    version: 1.0

logging:
  level:
    root: DEBUG

eureka:
  instance:
    preferIpAddress: true

  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "${EUREKA_SERVER:http://localhost:8070/eureka/}"