spring:
  application:
    name: userservice
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/userservice}"
    username: ${SPRING_DATASOURCE_USERNAME:neil}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081
  servlet:
    context-path: /userservice

info:
  message: "userservice default"

logging:
  level:
    root: DEBUG